env: "local"

http_server:
  address: "localhost:8040"
  timeout: "4s"
  idle_timeout: "60s"

redis:
  address: localhost:6389
  password: user1234
  user: testuser
  db: 0
  max_retries: 5
  dial_timeout: 10s
  timeout: 5s

postgres:
  username: 'postgres'
  host: 'localhost'
  port: '5444'
  dbname: 'postgres'
  sslmode: 'disable'